# Generated by Django 5.0 on 2025-09-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, default='0.00', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_content', models.FileField(upload_to='emr_files/')),
                ('billing_information', models.JSONField(blank=True, help_text='\n        Structured as:\n        {\n            "diagnosis_codes": [\n                {\n                    "code": str,\n                    "description": str,\n                    "type": "primary" | "secondary"\n                }\n            ],\n            "procedure_codes": [\n                {\n                    "cpt_code": str,\n                    "description": str,\n                    "estimated_cost": float  # in USD\n                }\n            ],\n            "total_estimate": float  # in USD\n        }\n        ', null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('medical_history', models.JSONField(blank=True, null=True)),
                ('family_history', models.JSONField(blank=True, null=True)),
                ('social_history', models.JSONField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, null=True)),
                ('medications', models.JSONField(blank=True, null=True)),
                ('vitals', models.JSONField(blank=True, null=True)),
                ('test_ordered', models.JSONField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('license_number', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMRComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emr.emr')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.healthcareprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.healthcareprofessional')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, default='')),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
                ('state', models.TextField(blank=True, default='')),
                ('zip', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('marital_status', models.CharField(blank=True, default='', max_length=20)),
                ('race_ethnicity', models.CharField(blank=True, default='', max_length=50)),
                ('insurance_provider', models.CharField(blank=True, default='', max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='emr',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.healthcareprofessional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHCPRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to='emr.healthcareprofessional')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hcp_relationships', to='emr.patient')),
            ],
            options={
                'unique_together': {('patient', 'hcp')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='healthcare_providers',
            field=models.ManyToManyField(related_name='patients', through='emr.PatientHCPRelationship', to='emr.healthcareprofessional'),
        ),
    ]
