# Generated by Django 5.0 on 2025-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emr',
            name='bmi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emr',
            name='height',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emr',
            name='weight',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
